# -*- coding: utf-8 -*-
"""flask_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4jGvyXsFPcE7MGxU-9GHjuVM-ceul6F
"""

!pip install flask-ngrok Pillow

import tensorflow as tf
from flask import Flask
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)  # Starts ngrok when app is run

@app.route("/")
def home():
    return "Hello from Flask on Google Colab!"

if __name__ == "__main__":
    app.run()